(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.logotipoeng = function() {
	this.initialize();

	// Línea de Gimnasios y Rascadores para Gatos
	this.instance = new lib.txt();
	this.instance.setTransform(380,55,1,1,0,0,0,241,17.5);

	// logoKTZ-110.png
	this.instance_1 = new lib.logotipo();
	this.instance_1.setTransform(59.5,55,1,1,0,0,0,59.5,55);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,312,189.5);


// symbols:
(lib.logoKTZ110 = function() {
	this.initialize(img.logoKTZ110);
}).prototype = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,119,110);


(lib.z = function() {
	this.initialize();

	// Capa 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABjhvQAAAGgHALIhKCMQgNAYAAAFQAAAIAXAAQAKAAAJgCQAJgCAEgDQAIgHAJgTQAEgJADgDQADgDAFAAQAMAAAGAIQAGAHAAAOQAAANgDALQgEAUgIAUIjNAAIgEgDQgDgDAAgHQAAgGAFgJIBXigQADgHAAgDQAAgKgTAAQgRAAgHAFQgIAGgJAWQgGAQgKAAQgJAAgHgJQgHgKAAgLQAAgTAOgbQALgTAGAAIAEACQAKADAjAAQAQAAA1gDIAwgDQAIAAAEAFQAFAEAAAHIAAAA").cp();
	this.shape.setTransform(11.6,12.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,23.2,25.7);


(lib.t = function() {
	this.initialize();

	// Capa 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AA0hUQAJAAAIAPQAJAOAAAPQAAALgGAFQgEADgGAAQgGAAgFgDQgDgEgFgIQgEgHgBgDQgDgCgDAAQgDAAgCAEQgCADAAAJIAABCQAAAKACAFQACAEAFADQAGADACACQACACAAAFQAAAJgKADQgLAFgWAAQgZAAgNgFQgMgEAAgJQAAgGAEgCQABgBAHgCQAFgBACgEQABgEAAgLQACgJAAgVQABgTAAgPQAAgLgBgFQgCgEgDAAQgFAAgDAGQgIANgEAEQgGAEgGAAQgGAAgEgEQgDgFAAgIQAAgHADgJQADgJAFgIQAIgMAIAAQADAAACABQAHABADAAQAEABAFAAIA3AAQAKAAAIgDQADgBACAAIAAAA").cp();
	this.shape_1.setTransform(7.9,8.5);

	this.addChild(this.shape_1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,15.7,17);


(lib.k = function() {
	this.initialize();

	// Capa 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AB1hxQAAAHgEAFQgDAFgFACQgFACgNAAQgJAAgFACQgFADgIAHIgTAVQgLALAAAJQAAAFADAFQACAFAHAJIBDBUQAJALAEAEQADACAHAEQAKAEAEAGQAEAGAAAIQAAAWgbAAIhFAAQgGAAgFgEQgEgDgJgNQgOgWgVgbQgKgMgEgEQgEgDgEAAQgKAAAAAVQAAASAHAGQABABAFAEQAJAHAAAKQAAANgQAGQgQAFglAAQgiAAgPgEQgGgCgEgFQgEgFAAgHQAAgKAKgIQAFgEACgEQACgEACgKQAEgXAAgvQAAg1gEgXQgCgKgCgEQgCgEgHgEQgKgHAAgLQAAgKAGgFQAHgGAOgDQASgEAcAAQAcAAAOAGQAMAGAAAOQAAAGgCADQgCADgHAIQgDACgDALQgCAKAAALQAAAQAHAAQAEAAADgEQAEgEAMgQQAMgTAAgGQAAgEgCgHQgCgEAAgFQAAgPANgGQAOgGAjAAQAcAAANAEQARAFAAAQIAAAA").cp();
	this.shape_2.setTransform(15.1,14);

	this.addChild(this.shape_2);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,30.1,27.9);


(lib.eff1 = function() {
	this.initialize();

	// Capa 1
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.lf(["rgba(0,0,0,0)","rgba(177,99,163,0.749)","rgba(222,68,195,0.749)","rgba(177,99,163,0.486)","rgba(0,0,0,0)"],[0,0.243,0.494,0.745,1],-84.9,0,85,0).s().p("ANSImI6jAAIAAxLIajAAIAARL").cp();
	this.shape_3.setTransform(85,55);

	this.addChild(this.shape_3);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,170,110);


(lib.maskg01 = function() {
	this.initialize();

	// Capa 1
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.rf(["#B163A3","rgba(177,99,163,0)"],[0.294,1],0,0,0,0,0,36.6).s().p("AECj2QBrBmAACQQAACRhrBmQhrBniXAAQiWAAhrhnQhrhmAAiRQAAiQBrhmQBrhnCWAAQCXAABrBnIAAAA").cp();

	this.addChild(this.shape_4);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-36.4,-34.9,73,70);


(lib.ey = function() {
	this.initialize();

	// Capa 1
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#B163A3").s().p("AA+hbIgoAAIAAADQACAAADAAQACAAADABQABABACABQACACAAACQAAACgDAGQgBAGgDAJQgCAJgEALQgCAKgEAJQgDAJgCAHQgBAFgCACQgCgEgDgJQgDgIgCgKQgDgJgDgJQgDgJgCgHQgDgIgCgFQgBgFAAgBQAAgFAEgBQAEgCAFAAIAAgDIg5AAIAAADQAJAAAEACQADABACADQAEALAFAMQAEANAFANQAFANAFANQAEAKAEAKQAEAKACAHQABAGAAABQAAABAAAEQgBAEgBAGQgCAFgCAHQgCAHgDAHIAAAAQgEgDgEgDQgDgDgGAAQgFAAgDADQgDADAAAGQAAAFAEADQAFADAFAAQAGAAAGgEQAFgFAEgKQAEgNADgQQAFgPAEgQQAGgNAEgPQAFgPAEgMQADgNAEgJQADgJABgEQABgEACgCQACgDADgBQADgBADAAQACAAAEAAIAAgD").cp();
	this.shape_5.setTransform(6.2,9.3);

	this.addChild(this.shape_5);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,12.4,18.6);


(lib.eR = function() {
	this.initialize();

	// Capa 1
	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#B163A3").s().p("AAAhfQgMAAgLAEQgLADgJAGQgIAHgGAKQgFAKAAAPQAAAIADAHQADAIAFAGQAFAGAGAEQAGADAHADQAGACAEABQAEACAEABQAEACAFACQADABAGACQAGACAGADQAFADAEAEQAEAFADAFQACAFAAAHQAAASgMALQgMALgRAAQgHAAgHgCQgIgDgEgCQgFgDgEgEQgFgFgEgGQgFgFgDgHQgEgHgCgHIgDAAIABA0IACAAQACgDADgDQACgDABAAQABAAADACQADACAGACQAGACAJACQAJABANAAQANAAAMgDQANgEAJgGQAJgHAFgKQAFgKAAgNQAAgSgKgNQgKgLgRgGQgFgBgFgCQgEgCgFgBQgEgBgEgCQgDgCgGgCQgNgFgIgIQgIgIAAgOQAAgJADgHQACgHAGgEQAFgFAHgCQAHgDAIAAQAJAAAIAFQAIAEAHAGQAGAHAFAIQAFAJADAIIADAAIAAgwIgDAAQgCADgCAEQgDADAAAAQgBAAgDgCQgCgCgGgDQgFgCgIgCQgJgCgKAAIAAAA").cp();
	this.shape_6.setTransform(6.4,9.6);

	this.addChild(this.shape_6);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,12.9,19.2);


(lib.eL = function() {
	this.initialize();

	// Capa 1
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#B163A3").s().p("AgChcIhTAAIAAADQAHAAAGADQAGACAEAEQABACABADQABAEAAAEQAAAEAAAEQAAAFAAAEIAAAyQAAAGAAAIQAAAIAAAHQAAAIAAAGQAAAGAAAEQAAAEAAAEQgBAEAAAEQgBAEgBADQgBADgBACQgEAEgGACQgGADgHABIAAACIClAAIAKg1IgDgBQgDAIgEAHQgDAHgFAGQgFAGgHAFQgHAFgKADQgEABgGABQgGAAgFABQgGAAgEAAQgFAAgCAAQgDAAgFAAQgFgBgFgBQgEgBgDgBQgEgBgBgCQgCgDAAgIQgBgHAAgJQAAgJAAgHQAAgHAAgHQAAgGAAgHQAAgIAAgHQAAgJAAgIQAAgIAAgHQAAgHAAgIQAAgHABgJQAAgIADgEQADgEAEgDQAEgCAFgBQAEgBAEAAIAAgD").cp();
	this.shape_7.setTransform(8.8,9.4);

	this.addChild(this.shape_7);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,17.7,18.8);


(lib.eG = function() {
	this.initialize();

	// Capa 1
	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#B163A3").s().p("ABNg2QAHALADANIAEAAIAAg7IgEAAQgBADgCABQgCADgBABQgCACgCABQgBABAAAAQgBAAgEgCQgEgDgIgEQgIgDgLgCQgMgEgQAAQgPAAgOAEQgNADgMAHQgKAGgIAIQgJAIgFAJQgFAIgCAHQgEAHgBAHQgCAHgBAGQgBAFAAADQAAAWAIARQAHASAOAMQAOANATAHQATAHAXAAQAPAAALgDQALgCAIgEQAIgDAEgCQAEgDAAAAQACAAADADQADAEAEAFIADAAIABg6IgEAAQgCAMgGAKQgHALgJAIQgJAIgMAFQgMAFgNAAQgRAAgNgHQgOgIgKgMQgKgMgFgQQgFgRAAgSQAAgQAFgQQAFgRAKgOQAJgNAOgIQAOgIAQAAQANAAAMAEQALAFAJAIQAKAIAGALIAAAA").cp();
	this.shape_8.setTransform(9.1,9.6);

	this.addChild(this.shape_8);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,18.2,19.2);


(lib.rec2 = function() {
	this.initialize();

	// Layer 1
	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#B163A3").s().p("AD6ClInzAAIAAlJIHzAAIAAFJ").cp();
	this.shape_9.setTransform(25,16.5);

	this.addChild(this.shape_9);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,50,33);


(lib.logotipo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// Capa 4
	this.instance = new lib.z();
	this.instance.setTransform(74.4,69.5,4,4,0,0,0,11.6,12.9);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(39).to({_off:false},0).to({scaleX:2.66,scaleY:2.66,y:69.3,alpha:0.5},10).to({scaleX:1,scaleY:1,alpha:0},19).to({_off:true},1).wait(212));

	// T
	this.instance_1 = new lib.t();
	this.instance_1.setTransform(54.3,70.1,4,4,0,0,0,7.9,8.5);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(19).to({_off:false},0).to({scaleX:2.66,scaleY:2.66,x:54.2,alpha:0.5},10).to({scaleX:1,scaleY:1,alpha:0},19).to({_off:true},21).wait(212));

	// K
	this.instance_2 = new lib.k();
	this.instance_2.setTransform(36.1,69.7,4,4,0,0,0,15.1,14);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(19).to({_off:false},0).to({scaleX:2.66,scaleY:2.66,y:69.6,alpha:0.5},10).to({scaleX:1,scaleY:1,x:36,y:69.5,alpha:0},19).to({_off:true},40).wait(212));

	// Capa 2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AEdhsQgeg3BahLQBPg0A2A5QAeA4hZBKQhQAzg2g4IAAAAAEfkYQg7BThIggQgygqA9hsQA8hUBIAgQAxAqg9BtIAAAAAHBBbQhKAQgcg3QgKgxBXgcQBJgQAcA1QAKAxhWAeIAAAAAD7ATQAFAEAAAHQAAAGgGALIhLCNQgMAYAAAFQAAAJAWAAQAKAAAJgCQAJgDAEgCQAIgHAJgUQAEgIADgDQADgDAFAAQAMAAAGAIQAGAHAAAOQAAANgDALQgFAXgJAXQglBkhoA1QhiA0h6gJQi0gRh6hjQhxhggFiiQADieCLhYQB7hVCdgCQCKAABNAsQBSAqAyBKQhriCjegOQikAAh0BeQhsBXgICJQAACFCABRQByBMClgGQBqgJApgcQAwgaAMggQAJgPgNgDIhOAAIgEgDQgDgEAAgHQAAgFAFgJIBXiiQADgHAAgDQAAgKgTAAQgRAAgHAFQgHAGgJAVQgHAQgKAAQgJAAgHgJQgGgJAAgLQAAgTAOgbQAKgTAGAAIAEACQALADAiAAQAQAAA3gDIAxgDQAHAAAEAFIAAAAAATkTQgqgFgBhkQAHhSA0gLQAsAFACBkQgIBSg2ALIAAAAAkKBAQgCAKAAAKQAAARAHAAQAEAAADgEQAEgEAMgQQAOgTAAgGQAAgEgEgHQgCgFAAgEQAAgPAOgGQAPgGAjAAQAcAAANAEQAQAFAAAQQAAAHgDAFQgEAFgFACQgEABgNABQgKAAgFACQgEACgIAIIgTAVQgLALAAAJQAAAFACAFQADAFAHAIIBDBWQAJAMADADQAEADAHADQAKAFAEAGQAEAFAAAJQAAAVgbAAIhFAAQgHAAgEgDQgEgEgJgNQgOgVgXgcQgKgMgEgDQgEgEgEAAQgKAAAAAVQAAASAHAHQABABAFADQAJAHAAALQAAANgQAGQgQAFglAAQgiAAgPgEQgGgCgEgFQgEgGAAgGQAAgLAKgHQAFgEACgEQACgFACgKQAEgWAAgvQAAg3gEgXQgCgKgCgEQgCgEgHgEQgKgHAAgLQAAgKAGgFQAHgGAOgDQASgEAcAAQAcAAAOAGQAMAFAAAPQAAAGgCADQgCADgHAHQgDADgDALIAAAAAAaB9QgEADgGAAQgGAAgFgDQgDgEgDgIQgEgHgBgDQgDgCgDAAQgDAAgCAEQgCADAAAJIAABDQAAAKACAFQACAFAFACQAGADACADQACACAAAEQAAAJgKAEQgLAEgWAAQgbAAgNgFQgLgEAAgJQAAgFAEgCQABgBAHgCQAEgCACgDQABgEABgLQABgJAAgVQABgVAAgPQAAgLgBgFQgCgEgDAAQgEAAgEAGQgIANgEAEQgGAEgGAAQgFAAgEgEQgEgFAAgIQAAgHADgJQADgJAFgIQAIgMAJAAQACAAADABQAGABAEAAQADABAFAAIA5AAQAKAAAGgDQADgBACAAQAJAAAIAPQAJAOAAAPQAAALgGAFIAAAA").cp();
	mask.setTransform(58.7,55);

	// Capa 3
	this.instance_3 = new lib.eff1();
	this.instance_3.setTransform(-59.9,55,1,1,0,0,0,55,55);

	this.instance_3.mask = mask;
	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({x:185},299).wait(1));

	// Capa 1
	this.instance_4 = new lib.logoKTZ110();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).wait(300));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-114.9,0,234,110);


(lib.rec3 = function() {
	this.initialize();

	// Layer 1
	this.instance_5 = new lib.rec2();

	this.addChild(this.instance_5);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,50,33);


(lib.rec4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// Layer 1
	this.instance_6 = new lib.rec3();

	this.timeline.addTween(cjs.Tween.get(this.instance_6).to({scaleX:0.1,x:45,alpha:0.23},7).to({scaleY:0.09,y:30.2,alpha:0.66},5).to({scaleX:0.84,x:1.4,alpha:0},10).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,50,33);


(lib.rec5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// Layer 31
	this.instance_7 = new lib.rec4();
	this.instance_7.setTransform(251,159,0.99,1.303,180);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(3).to({_off:false},0).to({_off:true},20).wait(1));

	// Layer 29
	this.instance_8 = new lib.rec4();
	this.instance_8.setTransform(123.5,159,1.56,1.303,0,180,0);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({_off:true},23).wait(1));

	// Layer 27
	this.instance_9 = new lib.rec4();
	this.instance_9.setTransform(123.5,159,1.47,1.303,180);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(2).to({_off:false},0).to({_off:true},21).wait(1));

	// Layer 25
	this.instance_10 = new lib.rec4();
	this.instance_10.setTransform(0,159,1,1.303,0,180,0);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(6).to({_off:false},0).to({_off:true},17).wait(1));

	// Layer 23
	this.instance_11 = new lib.rec4();
	this.instance_11.setTransform(251,74.5,0.99,1.258,0,0,180);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(9).to({_off:false},0).to({_off:true},14).wait(1));

	// Layer 21
	this.instance_12 = new lib.rec4();
	this.instance_12.setTransform(123.5,74.5,1.56,1.258);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(12).to({_off:false},0).to({_off:true},11).wait(1));

	// Layer 19
	this.instance_13 = new lib.rec4();
	this.instance_13.setTransform(123.5,74.5,1.47,1.258,0,0,180);
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(15).to({_off:false},0).to({_off:true},8).wait(1));

	// Layer 17
	this.instance_14 = new lib.rec4();
	this.instance_14.setTransform(0,74.5,1,1.258);
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(12).to({_off:false},0).to({_off:true},11).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(123.5,116,78,43);


(lib.txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{},true);

	// Capa 10
	this.instance_15 = new lib.ey();
	this.instance_15.setTransform(204.4,24,0.2,14.998,0,0,0,6,9.3);
	this.instance_15.alpha = 0.5;
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(84).to({_off:false},0).to({scaleY:5,y:23.5,alpha:1},9).to({regX:6.5,scaleX:0.1,scaleY:10,y:23.8,alpha:0.199},10).to({_off:true},1).wait(236));

	// G
	this.instance_16 = new lib.eG();
	this.instance_16.setTransform(339.7,17,0.1,12,0,0,0,10,9.6);
	this.instance_16.alpha = 0.5;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(64).to({_off:false},0).to({scaleX:0.3,scaleY:5,y:17.2,alpha:1},9).to({regX:9.9,scaleX:1,scaleY:1},10).to({_off:true},1).wait(256));

	// R
	this.instance_17 = new lib.eR();
	this.instance_17.setTransform(204.2,17.6,0.1,12,0,0,0,9.5,9.3);
	this.instance_17.alpha = 0.5;
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(19).to({_off:false},0).to({regX:9.8,scaleX:0.3,scaleY:5,y:17.4,alpha:1},9).to({scaleX:1,scaleY:1,x:207.2,y:17.2},10).to({_off:true},1).wait(301));

	// G
	this.instance_18 = new lib.eG();
	this.instance_18.setTransform(93.5,17,0.1,12,0,0,0,10,9.6);
	this.instance_18.alpha = 0.5;
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(24).to({_off:false},0).to({scaleX:0.2,scaleY:5,y:17.2,alpha:1},9).to({regX:9.9,scaleX:1,scaleY:1},10).to({_off:true},1).wait(296));

	// L
	this.instance_19 = new lib.eL();
	this.instance_19.setTransform(11.7,17.6,0.114,11.999,0,0,0,8.8,9.3);
	this.instance_19.alpha = 0.5;
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(74).to({_off:false},0).to({regX:8.7,scaleX:0.3,scaleY:5,y:17.4,alpha:1},9).to({regX:8.8,scaleX:1,scaleY:1,y:17.2},10).to({_off:true},1).wait(246));

	// eff
	this.instance_20 = new lib.rec5();
	this.instance_20.setTransform(-449.9,-319.9,3.092,2.969);
	this.instance_20.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_20).to({x:-389.8,alpha:1},22).to({_off:true},1).wait(317));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	var mask_1_graphics_14 = new cjs.Graphics().p("AbNhQIgmAkIAAADIATAAQAAARAAAWQAAAUAAAYQAAAEACAEQADAEADAEQAEADAFACQAFABAGAAQAIAAAGgCQAGgCAFgDQAFgEACgEQADgEACgEIgCgBQgEAFgFADQgFACgHAAQgJAAgGgGQgGgGAAgNIAAhCIAoAAIAIgQIgwAAIAAgXIgCAAAcfg3QAFgBAEAAQAHAAAGACQAFADAFAFQAEAFAEAGQAEAHADAIIACgBIgDggQgHgDgJgCQgIgCgLAAQgJAAgHADQgIACgFAFQgGAFgDAGQgEAGAAAIQAAAMAGAJQAGAGAKADQAFACAHACQAGABAHABQAJACAFAGQAFAFAAAIQAAAPgHAHQgHAHgNAAQgJAAgGgEQgGgDgEgGQgFgGgDgHQgDgHgCgGIgCAAIAAAiQAIAEALACQAKACALAAQAKAAAIgCQAJgCAHgFQAHgEAEgIQAEgHAAgKQAAgNgJgKQgIgHgLgCQgFgCgHgBQgHgCgGgBQgIgCgFgEQgGgEAAgKQAAgGACgFQACgEAEgDQADgDAEgCIAAAAAYfh4QgBADgCACQgCACgBACQgCACgCABQgBABgBAAQAAAAgEgDQgEgDgIgDQgIgEgMgCQgLgDgQAAQgRAAgOADQgOAEgLAGQgLAGgIAIQgIAIgFAJQgFAIgDAHQgDAHgBAHQgCAHgBAGQgBAGAAAFQAAAVAIAPQAHASAOAMQANANAUAHQATAHAYAAQAPAAALgDQALgCAIgDQAIgEAEgCQAEgDABAAQABAAAEAEQADADADAFIADAAIABg6IgDAAQgCAMgHAKQgGALgJAIQgKAIgLAFQgMAFgOAAQgRAAgOgHQgOgHgKgNQgKgMgFgQQgGgOAAgTQAAgSAGgQQAFgRAJgOQAKgNAOgIQAOgIASAAQANAAALAFQAMAFAJAIQAJAIAHAKQAHALADANIADAAIAAg7IgDAAAZbguQAEgCAFAAQAGAAAEACQAEACACACQACACABACQABACAAAAIAAAbQgDABgEACQgDACgFADQgFABgHAEQgHAEgIAFQgJAGgFAGQgGAHAAAHQAAAHACAFQACAEAEADQADADAEACQAFABAEAAQAHAAAGgCQAGgDAEgDQAFgEAEgEQADgEACgEIABABQAAANAHAFQAGAFAJAAQAGAAAEgCQAFgCADgEQAEgDACgFQACgFAAgFIgCAAQgBAEgCADQgDACgGAAQgFAAgEgEQgEgDAAgMQAAgJAAgHQAAgIAAgFQAAgHAAgHQAAgIAAgJQAAgFAAgEQAAgFgBgCQgDgFgGgDQgGgEgHAAQgDAAgFACQgGABgGADQgHACgHAEQgHAEgGAEQgCABgDACQgDABgCACQgCACgCADQgCACAAAEQAAADADADQADADAFAAQAEAAAEgCQADgDAAgEIAAgMQAAgBACgCQACgDADgCQADgCAEgBIAAAAAZeAIQAHgEAHgEQAHgCAFgDIAAAmQAAAEgDADQgFAFgFABQgFACgHAAQgHAAgFgGQgFgFAAgHQAAgGAFgGQAFgFAGgFIAAAAARnh0QgCgCgDgCQgDgCgDAAQgEgBgEAAQgIAAgIACQgIACgHAEQgHAEgFAFQgFAFgDAGQgDAGAAAKQgBALAAALIgQAAIgDALIATAAIAABjQAAACgCABQgDACgDABQgEABgEAAQgDABgDAAIAAADIBCAAIAAgDQgEAAgEgBQgEAAgDgBQgDAAgCgCQgCgBgBgCIAAhkIAcAAIADgLIgeAAQAAgKAAgHQAAgHAAgLQABgIACgFQACgEADgDQADgCADgBQADgBACAAQADABACADQADADACADQADAEADACQAEADAEAAQAFAAADgEQADgEAAgFQAAgDgCgDIAAAAASlg4QgKgEgLAAQgOAAgLAFQgMAGgIAIQgIAJgFALQgEALAAAKQAAARAGAMQAFAMAKAIQAJAIALAEQALAEAKAAQAMAAALgFQALgFAJgJQAIgJAFgMQAFgMAAgNQAAgOgGgLQgFgMgJgHQgJgIgLgEIAAAAASsgkQAFAJACAKQACAKAAAHQAAAJgCALQgCAKgFAKQgEAJgHAGQgHAGgKAAQgKAAgHgFQgIgFgEgIQgFgIgCgLQgCgKAAgMQAAgJACgLQADgKAFgJQAEgIAHgFQAHgGAJAAQAKAAAIAGQAHAGAEAIIAAAAAUig8QgJAAgGAFQgGAEgEAGQgFAGgDAGQgDAGgBADIAAAAIAAgkIgBAAIgjANIAAACQAEABADACQADACACACQACABAAABQABABAAACIAABWQAAAEgEACQgFACgGAAIAAADIA7AAIAAgDQgDAAgEgBQgDAAgDAAQgEgBgCgBQgDgBgBgDIAAhJQACgDACgFQACgEADgDQACgEADgCQADgCADAAQAEAAACABQACACACACQACABACACQADABAEAAQAEAAAEgEQADgDAAgGQAAgGgEgEQgFgEgGAAIAAAAAPCg1QgHgDgJgCQgIgCgLAAQgJAAgHADQgIACgFAFQgGAFgDAGQgEAGAAAIQAAAMAGAJQAGAGAKADQAFACAHACQAGABAHABQAJACAFAGQAFAFAAAIQAAAPgHAHQgHAHgNAAQgJAAgGgEQgGgDgEgGQgFgGgDgHQgDgHgCgGIgCAAIAAAiQAIAEALACQAKACALAAQAKAAAIgCQAJgCAHgFQAHgEAEgIQAEgHAAgKQAAgNgJgKQgIgHgLgCQgFgCgHgBQgHgCgGgBQgIgCgFgEQgGgEAAgKQAAgGACgFQACgEAEgDQADgDAEgCQAFgBAEAAQAHAAAGACQAFADAFAFQAEAFAEAGQAEAHADAIIACgBIgDggAMmghIAABWQAAAEgEACQgFACgGAAIAAADIA7AAIAAgDQgDAAgEgBQgDAAgDAAQgEgBgCgBQgDgBgBgDIAAhJQACgDACgFQACgEADgDQACgEADgCQADgCADAAQAEAAACABQACACACACQACABACACQADABAEAAQAEAAAEgEQADgDAAgGQAAgGgEgEQgFgEgGAAQgJAAgGAFQgGAEgEAGQgFAGgDAGQgDAGgBADIAAAAIAAgkIgBAAIgjANIAAACQAEABADACQADACACACQACABAAABQABABAAACIAAAAAMIgkQgEgIgGgFQgHgGgJgCQgJgDgKAAQgNAAgKAGQgKAFgHAIQgIAJgDALQgEALAAAKQAAAMAEAMQAEAMAIAJQAHAJALAFQALAFANAAQALAAAJgEQAJgEAGgGQAGgGAEgHQADgHABgGIgCAAQgDAJgJAHQgKAHgNAAQgMAAgJgFQgKgEgGgIQgFgIgEgKQgDgKAAgIQAAgDABgDQAAgDAAgCIBTAAQAAgLgFgIIAAAAALYgVQgFAAgFAAQgEAAgFAAQgFAAgGAAQABgDACgGQADgFAEgGQAEgGAGgEQAGgEAHAAQALAAAHAGQAHAHAAAKQAAAEgBABQgBACgCACQgDABgDABQgDAAgEAAQgGAAgFAAIAAAAAJcg5QgGADgGAEQgFAFgFAFQgEAFgEAFIAAgBIAAgdIgCAAIgmAPIAAACQADABAFADQAGACACABQACACAAABQABABAAACIAACOQAAACgDACQgCABgDABQgDABgEABQgEAAgCABIAAADIBAAAIAAgDQgDgBgDAAQgEAAgDgBQgDAAgDgCQgCgBgBgCQAAgFAAgHQAAgIAAgIQAAgHAAgIQAAgGAAgEQAFABAEAAQAFAAAFAAQARAAANgFQAOgFAJgJQAJgJAFgMQAFgNAAgMQAAgLgCgKQgDgKgGgIQgGgIgJgFQgJgFgMAAQgIAAgGADIAAAAAJAgcQACgDAEgEQAEgDAFgDQAFgCAHAAQAKAAAHAEQAIAEAFAGQAEAGADAJQACAJAAAHQAAAMgDALQgDAKgGAHQgFAHgHAEQgHAFgIAAQgJAAgFgEQgFgCgEgFQgDgFgBgGQgBgGgBgFQAAgGAAgGQAAgGAAgJQAAgEAAgGQAAgGAAgFQAAgCACgDIAAAAAIYAmIgCAAQgBAEgCADQgDACgGAAQgFAAgEgEQgEgDAAgMQAAgJAAgHQAAgIAAgFQAAgHAAgHQAAgIAAgJQAAgFAAgEQAAgFgBgCQgDgFgGgDQgGgEgHAAQgDAAgFACQgGABgGADQgHACgHAEQgHAEgGAEQgCABgDACQgDABgCACQgCACgCADQgCACAAAEQAAADADADQADADAFAAQAEAAAEgCQADgDAAgEIAAgMQAAgBACgCQACgDADgCQADgCAEgBQAEgCAFAAQAGAAAEACQAEACACACQACACABACQABACAAAAIAAAbQgDABgEACQgDACgFADQgFABgHAEQgHAEgIAFQgJAGgFAGQgGAHAAAHQAAAHACAFQACAEAEADQADADAEACQAFABAEAAQAHAAAGgCQAGgDAEgDQAFgEAEgEQADgEACgEIABABQAAANAHAFQAGAFAJAAQAGAAAEgCQAFgCADgEQAEgDACgFQACgFAAgFIAAAAAGdg4QgEgEgHAAQgIAAgGAFQgGAEgFAGQgEAGgDAGQgDAGgBADIgBAAIABgkIgCAAIgiANIAAACQADABADACQADACADACQACABAAABQAAABAAACIAABWQAAAEgEACQgEACgGAAIAAADIA6AAIAAgDQgDAAgDgBQgEAAgDAAQgDgBgDgBQgCgBgBgDIAAhJQABgDADgFQACgEACgDQADgEADgCQADgCADAAQAEAAACABQACACACACQABABADACQACABAEAAQAFAAADgEQAEgDAAgGQAAgGgFgEIAAAAAFCAaQgGAKgJAFQgKAGgQAAQgKAAgIgEQgIgEgGgHQgGgHgDgJQgDgKAAgKQAAgLADgJQADgJAFgHQAFgHAGgEQAHgFAIAAQALAAAFAHQAFAGAAAKQAAAFgBAEQABADAEADQADADAEAAQAGAAAEgEQAEgEAAgGQAAgHgEgGQgEgGgHgEQgGgEgIgCQgJgCgIAAQgNAAgLAFQgLAGgHAIQgIAJgFALQgEALAAALQAAANAEAMQAFALAHAJQAIAJAKAFQALAFAMAAQAKAAAJgDQAIgDAHgGQAHgFAEgHQAFgHACgHIgCgBAHOAIQAHgEAHgEQAHgCAFgDIAAAmQAAAEgDADQgFAFgFABQgFACgHAAQgHAAgFgGQgFgFAAgHQAAgGAFgGQAFgFAGgFIAAAAACXh0QAIAEAGAHQAHAGAFAJQAFAIADAJIADAAIAAgwIgDAAQgCADgDADQgCADgBAAQAAAAgDgCQgDgCgFgCQgFgCgJgCQgIgCgMAAQgMAAgMADQgLADgIAHQgJAHgFAKQgFAKAAAOQAAAIADAIQADAHAEAGQAFAGAGAFQAGAEAHADQAGACAEACQAFABAEACQAEABAEACQAFABAGADQAHACAFADQAGADAEACQAEAEACAFQACAGAAAHQAAASgMAKQgMALgTAAQgHAAgHgCQgHgDgFgCQgEgCgFgFQgFgEgEgGQgEgGgEgHQgEgGgCgHIgCAAIAAAzIADAAQACgCACgDQADgEABAAQABAAACACQAEACAFACQAGACAKACQAJACAMAAQAPAAANgEQAMgDAJgHQAJgHAFgKQAFgKAAgNQAAgQgJgMQgKgNgSgGQgFgCgEgBQgFgCgEgCQgFgBgEgBQgFgCgFgCQgNgFgJgIQgIgJAAgOQAAgIADgHQADgHAFgFQAGgEAHgDQAHgCAIAAQAKAAAJAEIAAAAAgshQQAAAHAAAHQAAAHAAAEQgFgCgHgCQgHgBgIAAQgPAAgMAFQgMAFgJAJQgJAIgEAMQgFAMAAALQAAAPAEAMQAEAMAHAIQAHAIAJADQAJAEAKAAQAPAAAKgGQALgGAHgOIAAAbIACAAIAmgLIAAgCQgFgCgFgDQgGgCgCgBIAAinIgCAAIgqALIAAACIAWAIQAAADAAAGQAAAGAAAHIAAAAAgsAdQgCALgIAHQgHAHgLAAQgKAAgIgEQgIgFgFgIQgFgHgDgKQgCgKAAgKQAAgKACgKQACgKAFgIQAFgIAHgEQAHgFAKAAQAIAAAIAHQAJAGAGALIAAA8AjNg5QgHADgFAEQgGAEgEAFQgEAFgDAFIgBgBIAAgcIgBAAIgiAMIAAACQADABADACQADACADABQABABABABQAAABAAACIAABYQAAAEgEACQgFACgGAAIAAADIAzAAIAAgDQgDAAgCgBQgDAAgBAAQgCgBgCgBQgBgBAAgDIAAhTQAHgHAFgDQAGgEAJAAQANAAAGAJQAGAJAAAPIAABAQAAAEgEABQgFABgHABIAAADIA1AAIAAgDQgCAAgDAAQgCgBgDAAQgCgBgCgBQgBgBAAgCIAAhLQAAgRgJgMQgIgLgPAAQgHAAgGADIAAAAAkRAmIgCAAQgBAEgDADQgDACgGAAQgFAAgEgEQgEgDAAgMQAAgJAAgHQAAgIAAgFQAAgHAAgHQABgIAAgJQAAgFgBgEQAAgFgBgCQgCgFgHgDQgGgEgGAAQgEAAgFACQgFABgHADQgGACgHAEQgHAEgHAEQgCABgDACQgCABgDACQgCACgCADQgBACAAAEQAAADADADQADADAEAAQAEAAAEgCQAEgDAAgEIAAgMQAAgBACgCQACgDADgCQADgCAEgBQAEgCAEAAQAGAAAEACQAEACACACQACACABACQABACAAAAIAAAbQgCABgEACQgEACgFADQgFABgGAEQgHAEgJAFQgIAGgGAGQgGAHAAAHQAAAHACAFQADAEADADQAEADAEACQAEABAEAAQAHAAAGgCQAGgDAFgDQAFgEADgEQAEgEACgEIAAABQAAANAHAFQAHAFAJAAQAFAAAFgCQAEgCAEgEQADgDACgFQACgFABgFIAAAAAndguQAEAFAEAGQAEAHADAIIACgBIgDggQgHgDgJgCQgIgCgLAAQgJAAgHADQgIACgFAFQgGAFgDAGQgEAGAAAIQAAAMAGAJQAGAGAKADQAFACAHACQAGABAHABQAJACAFAGQAFAFAAAIQAAAPgHAHQgHAHgNAAQgJAAgGgEQgGgDgEgGQgFgGgDgHQgDgHgCgGIgCAAIAAAiQAIAEALACQAKACALAAQAKAAAIgCQAJgCAHgFQAHgEAEgIQAEgHAAgKQAAgNgJgKQgIgHgLgCQgFgCgHgBQgHgCgGgBQgIgCgFgEQgGgEAAgKQAAgGACgFQACgEAEgDQADgDAEgCQAFgBAEAAQAHAAAGACQAFADAFAFIAAAAAlbAIQAHgEAHgEQAHgCAEgDIAAAmQAAAEgDADQgEAFgFABQgGACgGAAQgIAAgFgGQgEgFAAgHQAAgGAFgGQAEgFAHgFIAAAAApjg5QgGADgGAEQgFAFgEAFQgEAGgDAEIgBAAQgBgNgIgJQgIgIgMAAQgHAAgHADQgGADgFAEQgGAEgEAFQgEAFgDAFIAAgBIAAgcIgCAAIgiAMIAAADQADABADABQADACADACQACABAAABQAAABAAACIAABXQAAAEgEACQgEACgGAAIAAADIAyAAIAAgDQgCAAgDgBQgCAAgCAAQgCgBgBgBQgCgBAAgDIAAhTQAHgHAFgEQAGgDAIAAQAOAAAFAIQAFAJAAAPIAABBQAAAEgEABQgEABgHABIAAADIAzAAIAAgDQgCAAgDAAQgCgBgCAAQgCgBgCgBQgBgBAAgCIAAhSQAGgHAGgFQAGgEAIAAQAOAAAFAJQAGAIAAAQIAABAQAAAEgEABQgEABgHABIAAADIA0AAIAAgDQgDAAgCAAQgDgBgCAAQgCgBgCgBQgBgBAAgCIAAhMQAAgRgIgLQgIgLgPAAQgHAAgHADIAAAAAt8h2QgDAEgCADQgDADAAAAQgBAAgEgCQgFgDgIgDQgIgEgMgCQgMgDgQAAQgZAAgTAHQgSAIgMAMQgJAIgGAKQgGAKgDAJQgDAJgCAJQgBAIAAAHQAAAWAHAQQAHASAOAMQANAMAUAHQATAGAZAAQAMAAANgDQAMgCAKgEQALgEAHgDQAHgEACgCIAAgmQAAgFAAgEQAAgGACgDQADgEAFgCQAFgBAEgBIAAgCIhMAAIAAACQAPABAGAHQAFAFABAHQABAFAAAKQAAAJgBAIQgBAJgDADQgGAKgLAEQgKAEgNAAQgRAAgOgGQgNgHgKgMQgJgMgFgQQgFgPAAgVQAAgSAFgRQAFgRAKgMQAKgNANgIQAOgIARAAQAQAAANAGQAOAFAIAJQAGAHAGAKQAGALADALIADAAIAAg4IgDAAAsvg2IAAgDIg5AAIAAADQAJAAAEACQADABACADQAEALAFAMQAEANAFAMQAFAMAFANQAEAMAEAKQAEAKACAHQACAGABABQAAABgBAEQgCAEgBAGQgCAFgCAHQgCAHgDAHIgBAAQgDgDgEgDQgDgDgGAAQgFAAgDADQgDADAAAGQAAAFAEADQAFADAFAAQAGAAAGgEQAFgFAEgKQAEgNAFgQQAFgPAEgQQAFgPAFgPQAFgPAEgKQADgNADgJQADgJABgEQACgEACgCQACgDADgBQACgBADAAQADAAADAAIAAgDIgoAAIAAADQADAAACAAQADAAACABQACABACABQABACAAACQAAACgCAGQgBAGgDAJQgDAJgDALQgDAIgDAJQgDAJgCAHQgCAHgBACQgCgGgDgJQgDgIgDgKQgEgHgDgJQgDgJgDgHQgCgIgCgFQgBgFAAgBQAAgFAEgBQAEgCAFAAIAAAAAyChpQACgEADgDQADgCADgBQADgBABAAQADABADADQACADADADQADAEADACQADADAFAAQAFAAADgEQADgEAAgFQAAgDgCgDQgCgCgDgCQgDgCgEAAQgEgBgEAAQgIAAgIACQgIACgGAEQgHAEgFAFQgFAFgDAGQgDAGgBAKQAAALAAALIgRAAIgCALIASAAIAABjQAAACgCABQgCACgEABQgDABgEAAQgEABgDAAIAAADIBCAAIAAgDQgEAAgDgBQgEAAgDgBQgDAAgDgCQgCgBAAgCIAAhkIAbAAIAEgLIgfAAQAAgKAAgHQAAgHABgLQAAgIADgFIAAAAAzeg4QgLgEgKAAQgOAAgMAFQgLAGgJAIQgIAJgEALQgFALAAAKQAAARAGAMQAGAMAJAIQAJAIALAEQALAEAKAAQANAAALgFQALgFAIgJQAIgJAFgMQAFgMAAgNQAAgOgFgLQgGgMgJgHQgIgIgLgEIAAAAAzRgRQACAKAAAHQAAAJgCALQgCAKgEAKQgEAJgHAGQgHAGgKAAQgKAAgIgFQgHgFgFgIQgEgIgDgLQgCgKAAgMQAAgJADgLQACgKAFgJQAFgIAHgFQAHgGAIAAQALAAAHAGQAHAGAFAIQAEAJACAKIAAAAA2Pg5QgJgDgKAAQgNAAgKAGQgKAFgHAIQgIAJgDALQgEALAAAKQAAAMAEAMQAEAMAIAJQAHAJALAFQALAFANAAQALAAAJgEQAJgEAGgGQAGgGAEgHQADgHABgGIgCAAQgDAJgJAHQgKAHgNAAQgMAAgJgFQgKgEgGgIQgFgIgEgKQgDgKAAgIQAAgDABgDQAAgDAAgCIBTAAQAAgLgFgIQgEgIgGgFQgHgGgJgCIAAAAA2lgVQgFAAgFAAQgEAAgFAAQgFAAgGAAQABgDACgGQADgFAEgGQAEgGAGgEQAGgEAHAAQALAAAHAGQAHAHAAAKQAAAEgBABQgBACgCACQgDABgDABQgDAAgEAAQgGAAgFAAIAAAAA5+hvQgEgEgGAAQgGAAgEAEQgEAEAAAGQAAAGAEAEQAEAEAGAAQAGAAAEgEQAEgEAAgGQAAgGgEgEIAAAAA5QgjIAABYQAAAEgEACQgFACgGAAIAAADIAzAAIAAgDQgDAAgCgBQgDAAgBAAQgCgBgCgBQgBgBAAgDIAAhTQAHgHAFgDQAGgEAJAAQANAAAGAJQAGAJAAAPIAABAQAAAEgEABQgFABgHABIAAADIA1AAIAAgDQgCAAgDAAQgCgBgDAAQgCgBgCgBQgBgBAAgCIAAhLQAAgRgJgMQgIgLgPAAQgHAAgGADQgHADgFAEQgGAEgEAFQgEAFgDAFIgBgBIAAgcIgBAAIgiAMIAAACQADABADACQADACADABQABABABABQAAABAAACIAAAAA59g8IgkAMIAAABQAEABADACQAEACACABQACACAAABQABACAAACIAABXQAAACgCACQgCABgCABQgDABgDAAQgDABgDAAIAAADIA4AAIAAgDQgDAAgDgBQgCAAgDAAQgCgBgCgBQgBgBgBgDIAAhyIgBAAA6pAJQgDAIgEAHQgDAIgFAGQgFAGgHAEQgHAFgKADQgEABgGABQgGABgFAAQgGABgEAAQgFAAgCAAQgFAAgFgBQgFAAgFgBQgEgBgDgCQgEgBgBgBQgCgEAAgHQgBgIAAgIQAAgJAAgHQAAgHAAgFQAAgHAAgHQAAgHAAgJQAAgKAAgIQAAgHAAgIQAAgHAAgHQAAgIABgJQAAgHADgEQADgFAEgCQAEgCAFgBQAEgBAEgBIAAgDIhTAAIAAADQAHABAGACQAGADAEAEQABACABADQABADAAAEQAAAEAAAFQAAAEAAAFIAAAyQAAAHAAAIQAAAIAAAGQAAAHAAAGQAAAHAAADQAAAEAAAFQgBAEAAAEQgBAEgBADQgBADgBABQgEAEgGADQgGACgHABIAAADICnAAIAKg2IgDgB").cp();

	this.timeline.addTween(cjs.Tween.get(mask_1).to({graphics:null,x:0,y:0}).wait(14).to({graphics:mask_1_graphics_14,x:191,y:19.9}).wait(326));

	// circle
	this.instance_21 = new lib.maskg01("synched",0);
	this.instance_21.setTransform(297.5,19,1.457,1.457);
	this.instance_21.alpha = 0.25;
	this.instance_21._off = true;

	this.instance_21.mask = mask_1;
	this.timeline.addTween(cjs.Tween.get(this.instance_21).wait(14).to({startPosition:0,_off:false},0).to({scaleX:1.5,scaleY:1.5,x:108.5,alpha:1},39).to({scaleX:0.83,scaleY:0.83,x:354.5,y:18},20).to({scaleX:5,scaleY:5,x:352.5},30).to({scaleX:10,scaleY:10},40).wait(197));

	// circle
	this.instance_22 = new lib.maskg01("synched",0);
	this.instance_22.setTransform(111.5,19);
	this.instance_22.alpha = 0.25;
	this.instance_22._off = true;

	this.instance_22.mask = mask_1;
	this.timeline.addTween(cjs.Tween.get(this.instance_22).wait(14).to({startPosition:0,_off:false},0).to({scaleX:1.7,scaleY:1.7,x:238.5,alpha:1},39).to({scaleX:0.83,scaleY:0.83,x:64.5,y:18},20).to({scaleX:5,scaleY:5,x:122.5},30).to({scaleX:10,scaleY:10},40).wait(197));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68.1,24.4,241.2,127.7);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;